name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
        image: ghcr.io/nordsecurity/uniffi-rs-test-runner:v0.3.0
        options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        shell: bash
        env:
          # Github sets HOME to /github/home and breaks dependencies in Docker image..
          # https://github.com/actions/runner/issues/863
          HOME: /root
        run: |
          source ~/.bashrc
          # Disable debug info, because the job runs out of disk space
          RUSTFLAGS="-C debuginfo=0" cargo test
