name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
        image: ghcr.io/nordsecurity/uniffi-rs-test-runner:v0.0.1
        options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Set rust version
        run: |
          rustup show
          rustup update
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
           # Disable debug info, because the job runs out of disk space
           RUSTFLAGS="-C debuginfo=0" cargo build
      - name: Run tests
        shell: bash
        run: |
          HOME=/root . /root/.sdkman/bin/sdkman-init.sh
           # Disable debug info, because the job runs out of disk space
          RUSTFLAGS="-C debuginfo=0" cargo test
